### ISSUE TITLE
[Bug]不支持数组下标元素选取

### ISSUE THREAD

**Issue by 34benma** [zhegexiaohuozi/JsoupXpath#10]
示例网页：http://roll.fashion.sina.com.cn/style/celebrity/index.shtml
抓取元素：//html/body/div[@class='wrap']/div[@class='main clearfix']/div[@class='ml']/div[@class='blk_01']/div[@class='blk_tw tw01'][1]/h2/a

获取为空，但是如果抓取
//html/body/div[@class='wrap']/div[@class='main clearfix']/div[@class='ml']/div[@class='blk_01']/div[@class='blk_tw tw01']

就能正常获取

**Comment by zhegexiaohuozi** [comment]
即将发布的2.0 可以支持，随便搞
