### ISSUE TITLE
不支持最新的jsoup-1.10.2.jar 

### ISSUE THREAD

**Issue by chenxing890** [zhegexiaohuozi/JsoupXpath#14]
xpath : //table/tbody/tr[2]/   

使用最新的 jsoup-1.10.2 会报
 java.lang.NoSuchMethodError: org.jsoup.select.Elements.get(I)Lorg/jsoup/nodes/Element;

而使用jsoup-1.7.2 就不会有这个问题.

**Comment by zengzhaohu** [comment]
是从1.8.2以后版本就有这个问题，正在找修复此问题的版本

**Comment by zhegexiaohuozi** [comment]
即将发布2.0 采用了最新jsoup，语法解析器也进行了重构，更强大了，大家可以试试，并反馈我一些可能存在的问题，谢谢啦
