### ISSUE TITLE
运算符"|"的问题

### ISSUE THREAD

**Issue by Kamorj** [zhegexiaohuozi/JsoupXpath#24]
运算符"|"的功能是计算两个节点集，运算符"|"的两侧的xpath是相互独立的。而在使用JsoupXpath的过程中，运算符"|"的右侧xpath表达式是在左侧的正则表达式选取的节点上继续选取的，如果左侧xpath表达式未选取到结点，那么右侧的xpath表达式无论怎么写都没有效果。

**Comment by wtis-cj** [comment]
我也遇到了这个问题

**Comment by zhegexiaohuozi** [comment]
收到反馈，我会跟进

**Comment by zhegexiaohuozi** [comment]
已修复 https://github.com/zhegexiaohuozi/JsoupXpath/releases/tag/v2.2

**Comment by wtis-cj** [comment]
👍
