### ISSUE TITLE
//div[@class='postlary1']|//div[@class='postlary2'] 取出来的数据没有按照顺序来

### ISSUE THREAD

**Issue by sunashang** [zhegexiaohuozi/JsoupXpath#26]
postlary1
postlary2
postlary1
postlary2
然而取出来的数据是
postlary1
postlary1
postlary2
postlary2

**Comment by zhegexiaohuozi** [comment]
可以提供下完整的可以复现的测试数据吗？

**Comment by sunashang** [comment]
http://www.xx007.cn/dispbbs.asp?boardID=10&ID=22360046&page=1
这个网址的数据

**Comment by zhegexiaohuozi** [comment]
这个结果应该就是这样的，语义上你是先获取`postlary1 `的集合再获取的`postlary2 `的集合，然后对两个集合做union操作，结果就应该这样。

**Comment by zhegexiaohuozi** [comment]
按顺序来就调整下xpath语句呗

**Comment by zhegexiaohuozi** [comment]
譬如 :`//div[starts-with(@class,'postlary')]` 或是 `//div[@class='postlary1' or @class='postlary2']`

**Comment by sunashang** [comment]
好的，多谢。👍
