### ISSUE TITLE
//*[@id="list"]//dt[2]/following-sibling::dd 取得元素排序混乱,怎么才能顺序排列?

### ISSUE THREAD

**Issue by Antecer** [zhegexiaohuozi/JsoupXpath#30]
如图,取得的结果顺序是混乱的:
![image](https://user-images.githubusercontent.com/8684916/52135468-d6079000-2680-11e9-84e2-80f366d2e99c.png)

测试网址: https://www.biqudu.com/59_59722/

**Comment by Antecer** [comment]
经过测试,不适用兄弟选择器就是顺序排列的:
如:`//*[@id=\"list\"]//dd`
然而我的目的就是要排除前面一段的节点,而且前面这段需要排除的节点是不定数量的,需要通过某一个特征节点进行识别.

**Comment by zhegexiaohuozi** [comment]
收到反馈，我查查

**Comment by zhegexiaohuozi** [comment]
收到

**Comment by Antecer** [comment]
预计多久能够解决呢?想尽快用上.

**Comment by zhegexiaohuozi** [comment]
https://github.com/zhegexiaohuozi/JsoupXpath/releases/tag/v2.3.0  已发版

**Comment by zhegexiaohuozi** [comment]
maven中央库最迟明天应该会同步过去
