### ISSUE TITLE
a[text()='下一页']获取不到

### ISSUE THREAD

**Issue by QAQtutu** [zhegexiaohuozi/JsoupXpath#31]
分页的时候只能通过text()去定位，但是使用a[text()='下一页']取不到下一页这个节点

**Comment by zhegexiaohuozi** [comment]
- 确定HTML源码中确实有这个节点
- 看看是不是包含了空格或者其他字符，如果有尝试下`contains`函数

**Comment by Antecer** [comment]
还需要注意下有些网站的"下一页"中间是带空格的,比如"下 一 页".
