### ISSUE TITLE
不支持 not()选择的吗?

### ISSUE THREAD

**Issue by Antecer** [zhegexiaohuozi/JsoupXpath#33]
比如以下规则:
```//*[@id="chapters-list"]/li[not(@style)]```
测试地址:
```https://www.gxwztv.com/61/61514/```
JsoupXpath返回null

**Comment by zhegexiaohuozi** [comment]
支持，回头我确认下

**Comment by zhegexiaohuozi** [comment]
https://github.com/zhegexiaohuozi/JsoupXpath/releases/tag/v2.3.1
