### ISSUE TITLE
//*[text()^='工作经验' and text()$='工作经验'] 和  //*[text()='工作经验']

### ISSUE THREAD

**Issue by ztg-zlu** [zhegexiaohuozi/JsoupXpath#35]
[//*[text()^='工作经验' and text()$='工作经验']  可以取到值

用 //*[text()='工作经验']，却取不到值，为什么 ？？？

4. What version of JsoupXpath are you using（当前版本）?
2.3.0

图片怎么上传不了

**Comment by zhegexiaohuozi** [comment]
请按要求提交issue，谢谢

发自我的 iPhone

**Comment by zhegexiaohuozi** [comment]
至少给个能复现的页面

**Comment by ztg-zlu** [comment]
String sBody1 = "<span style=\"color: #5191ce;\" title=\"网页设计师\">网页设计师</span>";
        JXDocument jxd = JXDocument.create(sBody1);
        Object test1 = jxd.selOne("//*[text()^='网页设计师']");
        Object test2 = jxd.selOne("//*[text()$='网页设计师']");
        Object test3 = jxd.selOne("//*[text()='网页设计师']");
        System.out.println(test1);
        System.out.println(test2);
        System.out.println(test3);
test1,test2都可以取到span元素，test3取不到值，如果，我想完全相等的话，应该怎么实现

**Comment by zhegexiaohuozi** [comment]
不好意思，不清楚

**Comment by Antecer** [comment]
@ztg-zlu 你为什么不通过title选择呢?
```//*[@title="网页设计师"]```

**Comment by ztg-zlu** [comment]
@Antecer 他并不是每次都是一样的呀，如果不一样了，怎么办？
我现在是用，~=^网页设计师$,正则这种，凑活着用

**Comment by Antecer** [comment]
@ztg-zlu 我觉得你应该提供一个用于测试的网页地址.

**Comment by ztg-zlu** [comment]
我上面有个小点的代码，就可以测试了

**Comment by ztg-zlu** [comment]
@Antecer 我上面有个小点的代码，就可以测试了

**Comment by zhegexiaohuozi** [comment]
下一个版本会修复

**Comment by zhegexiaohuozi** [comment]
fixed in [V2.3.2](https://github.com/zhegexiaohuozi/JsoupXpath/releases/tag/v2.3.2)
