### ISSUE TITLE
无法以html根节点匹配

### ISSUE THREAD

**Issue by zctmdc** [zhegexiaohuozi/JsoupXpath#38]
Please answer these questions before submitting your issue. Thanks!

1. What did you do（使用的表达式与使用场景，确保能够复现）?
If possible, provide a recipe for reproducing the error.
测试地址：[https://www.qq.com/](https://www.qq.com/)
Xpath：`"/html/body/p[1]/font/font/text()"`
代码：
``` 
    Document doc = Jsoup.connect("https://www.qq.com").get();
    JXDocument jxd = JXDocument.create(doc);
    System.out.println(jxd.selNOne("//body/div[1]/div[3]/div/ul/li[1]/a/text()"));
```

2. What did you expect to see（期望看到什么）?
>新闻

3. What did you see instead（JsoupXpath给出的结果）?
   它提我提醒我Xpath语法错误：
```
org.seimicrawler.xpath.exception.XpathSyntaxErrorException: Please check the syntax of your xpath expr or commit a InputMismatchException: 
	at org.seimicrawler.xpath.JXDocument.selN(JXDocument.java:128)
	at org.seimicrawler.xpath.JXDocument.selNOne(JXDocument.java:146)
	at testcase.JsoupTest.testName04(JsoupTest.java:102)
```
4. What version of JsoupXpath are you using（当前版本）?
```
	<!-- https://mvnrepository.com/artifact/org.jsoup/jsoup -->
		<dependency>
			<groupId>org.jsoup</groupId>
			<artifactId>jsoup</artifactId>
			<version>1.11.3</version>
		</dependency>
	<!-- https://mvnrepository.com/artifact/cn.wanghaomiao/JsoupXpath -->
		<dependency>
			<groupId>cn.wanghaomiao</groupId>
			<artifactId>JsoupXpath</artifactId>
			<version>2.3.2</version>
		</dependency>
```

5. 其他测试：
   在console使用
    `$x(XPATH_STRING)[0]`
	`document.evaluate(XPATH_STRING, document, null,XPathResult.ANY_TYPE, null).iterateNext()`
	语法可以达到预期结果：新闻
	[![A1ikBd.png](https://s2.ax1x.com/2019/03/21/A1ikBd.png)](https://imgchr.com/i/A1ikBd)
    然后我使用不包含html节点的xpath在java代码中得到了我想要的结果：
    `//body/div[1]/div[3]/div/ul/li[1]/a/text()")[0]`
    我可以直接使用body为根节点去匹配也可以达到预期：
    `/body/div[1]/div[3]/div/ul/li[1]/a/text()")[0]`
     请问，它一开始就是他如此设计的么？
    但是我觉得能在console中得到结果，且传入的节点是以html为根节点的，在此程序中应该以html为根节点来计算。
    而且我在debug中看到得到的doc和jxd都是html为根节点的
    [![A1iL28.png](https://s2.ax1x.com/2019/03/21/A1iL28.png)](https://imgchr.com/i/A1iL28)

**Comment by zhegexiaohuozi** [comment]
在JsoupXpath中，支持了自定义的NodeTest，`html()`获取全部节点的内部的html，`html()` 会和根节点的 html标签冲突，所以这种xpath语句 `/html/body/div`会提示语法错误，因为解析器期待的是`html()`而不是`html`.这个暂时不考虑把`html()`这个自定义的NodeTest命名改掉，毕竟有人已经在大量使用了。对于和根节点标签`html`冲突，还是很好绕过的。

**Comment by zhegexiaohuozi** [comment]
```
NodeType:  'comment'
  |  'text'
  |  'processing-instruction'
  |  'node'
  |  'num'                                              //抽取数字
  |  'allText'                                          //提取节点下全部文本
  |  'outerHtml'                                        //获取全部节点的 包含节点本身在内的全部html
  |  'html'                                             //获取全部节点的内部的html
  ;
```
