### ISSUE TITLE
如何猎取元素索引？？？

### ISSUE THREAD

**Issue by ztg-zlu** [zhegexiaohuozi/JsoupXpath#39]
Please answer these questions before submitting your issue. Thanks!

1. What did you do（使用的表达式与使用场景，确保能够复现）?
If possible, provide a recipe for reproducing the error.

2. What did you expect to see（期望看到什么）?
我用“//th[text()='姓名']”取到元素时，我想知道它是第几个?应该怎么取？
表单，不知道列的位置，只能通过表头判断，所以，我的想法是，通过表头，取得元素的索引，再通过索引取得td的值

3. What did you see instead（JsoupXpath给出的结果）?

4. What version of JsoupXpath are you using（当前版本）?

**Comment by zhegexiaohuozi** [comment]
返回结果如果是节点的话，`JXNode`可以转为`Element`，通过 `Element`你就可以随便拿到原始节点的上下文信息。
