### ISSUE TITLE
发现BUG一枚: //*[preceding-sibling::text()[1]="最新章节："]选取不到元素

### ISSUE THREAD

**Issue by booksources** [zhegexiaohuozi/JsoupXpath#41]
目标测试网页:
https://www.caimoge.com/search/3055/1.html
以下表达式在Chrome测试通过:
`//*[preceding::text()[1]="最新章节："]/text()`
`//*[preceding-sibling::text()[1]="最新章节："]/text()`
实际使用的时候发现无法选取到元素.

**Comment by zhegexiaohuozi** [comment]
https://github.com/zhegexiaohuozi/JsoupXpath/issues/52  会做统一修复
