### ISSUE TITLE
单个节点使用多个条件获取不到元素

### ISSUE THREAD

**Issue by hehejl666** [zhegexiaohuozi/JsoupXpath#42]
Please answer these questions before submitting your issue. Thanks!

1. What did you do（使用的表达式与使用场景，确保能够复现）?
If possible, provide a recipe for reproducing the error.

[http://kaijiang.zhcw.com/zhcw/html/ssq/list_1.html](url)
`//*/table[@class='wqhgt']/tbody/tr[position()>2 and position()<last()]`
使用 xpathHelper 能够获取到元素

2. What did you expect to see（期望看到什么）?
对应页面上的列表记录

3. What did you see instead（JsoupXpath给出的结果）?

0条记录

4. What version of JsoupXpath are you using（当前版本）?

当前版本 2.3.2

**Comment by zhegexiaohuozi** [comment]
`last()`函数没有使用绝对值的问题，下一版修复
