### ISSUE TITLE
获取text时无法排除掉当前节点下面某些节点text

### ISSUE THREAD

**Issue by iLibra** [zhegexiaohuozi/JsoupXpath#43]
Please answer these questions before submitting your issue. Thanks!

1. What did you do（使用的表达式与使用场景，确保能够复现）?
If possible, provide a recipe for reproducing the error.

对于`<div class='a'> a <div>need</div> <div class='e'> not need</div> c </div>`

2. What did you expect to see（期望看到什么）?
a need c

3. What did you see instead（JsoupXpath给出的结果）?
现在要么是用allText()得到的是 a need not need c
要么得到的是 a c
无法实现得到 a need c 

4. What version of JsoupXpath are you using（当前版本）?
2.3.2

**Comment by zhegexiaohuozi** [comment]
https://github.com/zhegexiaohuozi/JsoupXpath/issues/44
