### ISSUE TITLE
解析出来的结果可以增加一些其他的信息，比如说在源文件的位置等

### ISSUE THREAD

**Issue by lwclover** [zhegexiaohuozi/JsoupXpath#48]
Please answer these questions before submitting your issue. Thanks!

1. What did you do , If possible, provide a recipe for reproducing the error.（使用的表达式与使用场景，确保能够复现）?

2. What did you expect to see（期望看到什么）?
解析出来的结果可以增加一些其他的信息，比如说在源文件的位置（行数）信息

3. What did you see instead（JsoupXpath给出的结果）?

4. What version of JsoupXpath are you using（当前版本）?
2.3.2

**Comment by zhegexiaohuozi** [comment]
欢迎提交PR
