### ISSUE TITLE
亲还不支持string(.)方法

### ISSUE THREAD

**Issue by zhymin77** [zhegexiaohuozi/JsoupXpath#50]
能否尽快支持string(xpath)方法，像：“string(//label[@class='filter-item J-filter-common']/.)”，像scrapy那样

**Comment by zhegexiaohuozi** [comment]
请参考文档，[开发者添加函数
](https://github.com/zhegexiaohuozi/JsoupXpath#%E5%BC%80%E5%8F%91%E8%80%85%E6%B7%BB%E5%8A%A0%E5%87%BD%E6%95%B0)
