### ISSUE TITLE
html()提取内容和原html不符

### ISSUE THREAD

**Issue by CrazyShaQuiShi** [zhegexiaohuozi/JsoupXpath#57]
jxDocument.selN("//div[@class='ewb-main']/html()")
提取出来的网页内容对于&nbsp; 中部分内容处理后剩下&nbsp

**Comment by zhegexiaohuozi** [comment]
请按模板补充以下内容便于复现和验证

1. What did you do , If possible, provide a recipe for reproducing the error.（使用的表达式与使用场景，确保能够复现）?


2. What did you expect to see（期望看到什么）?



3. What did you see instead（JsoupXpath给出的结果）?



4. What version of JsoupXpath are you using（当前版本）?
