### ISSUE TITLE
`text()`重构后文本比对逻辑没有同步更新导致的。2.4.3已修复。JsoupXpath表现行为和Xpath1.0标准语法以及Chrome的实现保持一致。Chrome的实现可以通过 `$x("//*[text()='总字数']//text()")`来验证。JsoupXpath的test如下：

### ISSUE THREAD

**Issue by gedoor** [zhegexiaohuozi/JsoupXpath#59]
`text()`重构后文本比对逻辑没有同步更新导致的。2.4.3已修复。JsoupXpath表现行为和Xpath1.0标准语法以及Chrome的实现保持一致。Chrome的实现可以通过 `$x("//*[text()='总字数']//text()")`来验证。JsoupXpath的test如下：
https://github.com/zhegexiaohuozi/JsoupXpath/blob/5053ad5da737d7e72c2b165203f9fc5ab2164511/src/test/java/org/seimicrawler/xpath/JXDocumentTest.java#L264

_Originally posted by @zhegexiaohuozi in https://github.com/zhegexiaohuozi/JsoupXpath/issues/53#issuecomment-720368096_
```
//*[text()='总字数']//text() 可以获取正确结果
//*[text()='总字数']//text()[0] 获取不到结果
```

**Comment by zhegexiaohuozi** [comment]
和Chrome行为保持一致

**Comment by gedoor** [comment]
最新版本text()不是返回数组可以用[0]获取吗,这个获取不到结果

**Comment by gedoor** [comment]
> 和Chrome行为保持一致

最新版本text()不是返回数组可以用[0]获取吗,这个获取不到结果

**Comment by zhegexiaohuozi** [comment]
索引都是从1开始的

**Comment by zhegexiaohuozi** [comment]
可能你的理解有误，可以通过Chrome做测试验证

**Comment by zhegexiaohuozi** [comment]
jsoupxpath的实现会和Chrome的保持一致

**Comment by gedoor** [comment]
> 索引都是从1开始的

好的,明白了,我以为从0开始的
