### ISSUE TITLE
取到元素

### ISSUE THREAD

**Issue by CodeLieutenant** [zhegexiaohuozi/JsoupXpath#6]
在 0.2.2以及之前所有版本，是不能返回元素，对吗
比如：
rs = jxDocument.sel("//table[1]");
通过该方法，获得的rs总是空，简单看了代码，是如果最后是table等元素级别，而不是text等函数或者@等，那么则返回是空，是吧

**Comment by CodeLieutenant** [comment]
如果确认是这样，那么如果爬取这些列表，需要循环的情况怎么处理呢，
比如
http://www.boc.cn/sourcedb/whpj/index.html
爬取各个国家汇率，需要先拿到这个table，然后，遍历所有tr。安装目前的情况，是无法处理的。
想知道，您是怎么处理的呢

**Comment by zhegexiaohuozi** [comment]
先这样用 //table/tbody/tr
递归下的直接元素提取确实有bug，会尽快修复。



大家有什么问题或建议现在都可以选择通过下面的邮件列表讨论，首次发言前需先订阅并等待审核通过（主要用来屏蔽广告宣传等）
订阅:请发邮件到 seimicrawler+subscribe@googlegroups.com
发言:请发邮件到 seimicrawler@googlegroups.com
退订:请发邮件至 seimicrawler+unsubscribe@googlegroups.com
 
发件人： CodeLieutenant
发送时间： 2016-06-14 11:31
收件人： zhegexiaohuozi/JsoupXpath
主题： Re: [zhegexiaohuozi/JsoupXpath] 取到元素 (#6)
如果确认是这样，那么如果爬取这些列表，需要循环的情况怎么处理呢，
比如
http://www.boc.cn/sourcedb/whpj/index.html
爬取各个国家汇率，需要先拿到这个table，然后，遍历所有tr。安装目前的情况，是无法处理的。
想知道，您是怎么处理的呢
―

**Comment by zhegexiaohuozi** [comment]
v0.3.1中已修复

**Comment by CodeLieutenant** [comment]
辛苦，感谢。
