### ISSUE TITLE
请问xpath的matches(string,pattern)方法有吗

### ISSUE THREAD

**Issue by huangxuchu** [zhegexiaohuozi/JsoupXpath#61]
org.seimicrawler.xpath.exception.XpathSyntaxErrorException: Please check the syntax of your xpath expr or commit a NoSuchFunctionException: not support function: matches

**Comment by zhegexiaohuozi** [comment]
目前没有实现，欢迎参考开发者文档，为项目贡献该函数 ，参考：https://github.com/zhegexiaohuozi/JsoupXpath#%E5%BC%80%E5%8F%91%E8%80%85%E6%B7%BB%E5%8A%A0%E5%87%BD%E6%95%B0

另外，JsoupXpath可以使用  `~=` 操作符更便捷的做正则匹配条件检测
