### ISSUE TITLE
num()函数提取整数自动转为小数

### ISSUE THREAD

**Issue by Ruffianjiang** [zhegexiaohuozi/JsoupXpath#63]
Please answer these questions before submitting your issue. Thanks!

1. What did you do , If possible, provide a recipe for reproducing the error.（使用的表达式与使用场景，确保能够复现）?  

`<div>2</div>`  

//div/num()

2. What did you expect to see（期望看到什么）?

期望提取后为2

3. What did you see instead（JsoupXpath给出的结果）?

实际结果2.0

4. What version of JsoupXpath are you using（当前版本）?

2.5.0

**Comment by zhegexiaohuozi** [comment]
目前的设定是这样的，如果想取原始文本用 `text()`函数即可

**Comment by Ruffianjiang** [comment]
> 目前的设定是这样的，如果想取原始文本用 `text()`函数即可

因为数字在一串文本里，比如"收到102封邮件"，解出来102.0，违反所见即所得的原则。

其他的一些函数有计划支持吗，比如 tokenize

**Comment by zhegexiaohuozi** [comment]
还是优化了，符合使用直觉。https://github.com/zhegexiaohuozi/JsoupXpath/releases/tag/v2.5.1
