### ISSUE TITLE
文档中的轴描述错误

### ISSUE THREAD

**Issue by Ruffianjiang** [zhegexiaohuozi/JsoupXpath#64]
Please answer these questions before submitting your issue. Thanks!

1. What did you do , If possible, provide a recipe for reproducing the error.（使用的表达式与使用场景，确保能够复现）?
readme文档描述错误： 
```
 |  'following-sibling-one'  //在上下文中节点的前一个同胞节点中选择（JsoupXpath扩展）
  |  'preceding-sibling-one'  //在上下文中节点的下一个同胞节点选择(JsoupXpath扩展)
```
2. What did you expect to see（期望看到什么）?

3. What did you see instead（JsoupXpath给出的结果）?
`following-sibling-one`实际是下一个同胞节点
`preceding-sibling-one`实际解到的是自己

4. What version of JsoupXpath are you using（当前版本）?
2.5.0

**Comment by zhegexiaohuozi** [comment]
下一版修正描述
