### ISSUE TITLE
轴函数获取节点顺序错误 preceding-sibling

### ISSUE THREAD

**Issue by Ruffianjiang** [zhegexiaohuozi/JsoupXpath#65]
Please answer these questions before submitting your issue. Thanks!

1. What did you do , If possible, provide a recipe for reproducing the error.（使用的表达式与使用场景，确保能够复现）?
```
<div>1</div>
<div>2</div>
<div>3</div>
<div>4</div>
<div>5</div>
```

```
node.selOne("/div[text()=3]").selOne("preceding-sibling::div[1]/text()"); // 期望是2
node.selOne("/div[text()=5]").selOne("preceding-sibling::div[1]/text()"); // 期望是4
```

2. What did you expect to see（期望看到什么）?

期望是同胞节点的上一个

3. What did you see instead（JsoupXpath给出的结果）?

实际解到的都是1

4. What version of JsoupXpath are you using（当前版本）?
2.5.0

**Comment by zhegexiaohuozi** [comment]
以当前实现为准吧。
- `//div[text()='3']/preceding-sibling::div[-1]/text()`  取倒序索引可以用负数，如 `-1`
