### ISSUE TITLE
选择包含某个属性的元素

### ISSUE THREAD

**Issue by CodeLieutenant** [zhegexiaohuozi/JsoupXpath#9]
div[@href='www.baidu.com']
如上，如果我的要求是选择出带有href的div，对href值不做要求。现在有这样的方法吗
类似于xpath中这种使用方法（http://stackoverflow.com/questions/3737906/xpath-how-to-check-if-an-attribute-exists）

**Comment by zhegexiaohuozi** [comment]
2.0支持，近期就发版了，大家也可以先体验体验新版，并反馈我一些可能存在的问题，谢谢啦
